// Complete Contract ABIs from original HTML dashboard
export const FACTORY_ABI = [
  'function owner() view returns (address)',
  'function pendingOwner() view returns (address)',
  'function migrator() view returns (address)',
  'function creationFee() view returns (uint256)',
  'function defaultVirtualBNB() view returns (uint256)',
  'function defaultMigrationTarget() view returns (uint256)',
  'function standardImpl() view returns (address)',
  'function taxImpl() view returns (address)',
  'function reflectionImpl() view returns (address)',
  'function vestingWallet() view returns (address)',
  'function managers(address) view returns (bool)',
  'function timelockExpiry(bytes32) view returns (uint256)',
  'function setVestingWallet(address)',
  'function setCreationFee(uint256)',
  'function setDefaultParams(uint256,uint256)',
  'function addManager(address)',
  'function removeManager(address)',
  'function cancelAction(bytes32)',
  'function transferOwnership(address)',
  'function acceptOwnership()',
  'function rescueBNB(address)',
  'function rescueToken(address,address)',
  'function proposeSetPlatformFee(uint256)',
  'function executeSetPlatformFee()',
  'function proposeSetCharityFee(uint256)',
  'function executeSetCharityFee()',
  'function proposeSetFeeRecipient(address)',
  'function executeSetFeeRecipient()',
  'function proposeSetCharityWallet(address)',
  'function executeSetCharityWallet()',
  'function proposeSetRouter(address)',
  'function executeSetRouter()',
  'function predictTokenAddress(address,bytes32,address) view returns (address)',
  'function createToken((string name,string symbol,uint8 supplyOption,bool enableCreatorAlloc,bool enableAntibot,uint256 antibotBlocks,string metaURI,bytes32 salt)) payable returns (address)',
] as const

export const BC_ABI = [
  'function factory() view returns (address)',
  'function deployer() view returns (address)',
  'function pancakeRouter() view returns (address)',
  'function setFactory(address)',
  'function feeRecipient() view returns (address)',
  'function charityWallet() view returns (address)',
  'function platformFee() view returns (uint256)',
  'function charityFee() view returns (uint256)',
  'function totalTokensLaunched() view returns (uint256)',
  'function allTokens(uint256) view returns (address)',
  'function getTokensByCreator(address) view returns (address[])',
  'function getToken(address) view returns (tuple(address token,address creator,uint256 totalSupply,uint256 liquidityTokens,uint256 creatorTokens,uint256 bcTokensTotal,uint256 bcTokensSold,uint256 virtualBNB,uint256 k,uint256 raisedBNB,uint256 migrationTarget,address pair,address router,bool antibotEnabled,uint256 creationBlock,uint256 tradingBlock,bool migrated))',
  'function getAmountOut(address,uint256) view returns (uint256 tokensOut,uint256 feeBNB)',
  'function getAmountOutSell(address,uint256) view returns (uint256 bnbOut,uint256 feeBNB)',
  'function getSpotPrice(address) view returns (uint256 price)',
  'function buy(address,uint256,uint256) payable',
  'function sell(address,uint256,uint256,uint256)',
  'function migrate(address)',
] as const

export const VW_ABI = [
  'function owner() view returns (address)',
  'function factory() view returns (address)',
  'function VESTING_DURATION() view returns (uint256)',
  'function schedules(address,address) view returns (uint256 total,uint256 start,uint256 claimed)',
  'function claimable(address,address) view returns (uint256)',
  'function claim(address)',
  'function addVesting(address,address,uint256)',
  'function voidSchedule(address,address)',
  'function setFactory(address)',
  'function transferOwnership(address)',
] as const

export const VAULT_ABI = [
  'function THRESHOLD() view returns (uint8)',
  'function SIGNER_COUNT() view returns (uint8)',
  'function signers(uint256) view returns (address)',
  'function isSigner(address) view returns (bool)',
  'function proposalCount() view returns (uint256)',
  'function confirmed(uint256,address) view returns (bool)',
  'function getProposal(uint256) view returns (tuple(address,uint256,bytes,address,uint8,bool,bool))',
  'function propose(address,uint256,bytes) returns (uint256)',
  'function confirm(uint256)',
  'function revoke(uint256)',
  'function execute(uint256)',
  'function cancel(uint256)',
  'function getSignerConfirmations(uint256) view returns (bool[3])',
  'function getProposalRange(uint256,uint256) view returns (uint256[],address[],uint256[],address[],uint8[],bool[],bool[])',
] as const

export const COLLECTOR_ABI = [
  'function owner() view returns (address)',
  'function pendingOwner() view returns (address)',
  'function CR8() view returns (address)',
  'function MTN() view returns (address)',
  'function BB() view returns (address)',
  'function TW() view returns (address)',
  'function HK() view returns (address)',
  'function KJC() view returns (address)',
  'function lastDisperse() view returns (uint256)',
  'function lastRecipientUpdate() view returns (uint256)',
  'function disperseCooldownRemaining() view returns (uint256)',
  'function recipientCooldownRemaining() view returns (uint256)',
  'function Disperse()',
  'function setRecipients(address,address,address,address,address,address)',
  'function rescueToken(address,uint256)',
  'function transferOwnership(address)',
  'function acceptOwnership()',
] as const

export const ONE_MEMEBB_ABI = [
  'function owner() view returns (address)',
  'function pendingOwner() view returns (address)',
  'function router() view returns (address)',
  'function buyToken() view returns (address)',
  'function cooldown() view returns (uint256)',
  'function lastBuyAt() view returns (uint256)',
  'function cooldownRemaining() view returns (uint256)',
  'function BBnow()',
  'function setRouter(address)',
  'function setBuyToken(address)',
  'function setCooldown(uint256)',
  'function rescueToken(address,uint256)',
  'function withdrawBNB(uint256)',
  'function transferOwnership(address)',
  'function acceptOwnership()',
] as const

export const ERC20_ABI = [
  'function name() view returns (string)',
  'function symbol() view returns (string)',
  'function decimals() view returns (uint8)',
  'function balanceOf(address) view returns (uint256)',
  'function allowance(address,address) view returns (uint256)',
  'function approve(address,uint256) returns (bool)',
] as const
